---
kind: pipeline
type: docker
name: production
trigger:
  branch:
    include:
      - master
steps:
  - name: build
    image: plugins/docker
    settings:
      repo: rg.nl-ams.scw.cloud/silvergh0st/dntskdev
      tags: production
      registry: rg.nl-ams.scw.cloud/silvergh0st
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: cloud.lyalyuev.info
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /opt
        - docker-compose pull dntskdev
        - docker-compose up -d --remove-orphans
    depends_on:
      - build
